// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnyIpG7ksIsK8aZbGhAvkNPioK3mi1tvo',
    appId: '1:374257279074:android:04420308badd82d7faf13b',
    messagingSenderId: '374257279074',
    projectId: 'tiktok-clone-flutter-cc8cd',
    storageBucket: 'tiktok-clone-flutter-cc8cd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCsnpZDwS3Afn7byAIKVtolTxxwwnFDYw',
    appId: '1:374257279074:ios:cf754658dd5b04abfaf13b',
    messagingSenderId: '374257279074',
    projectId: 'tiktok-clone-flutter-cc8cd',
    storageBucket: 'tiktok-clone-flutter-cc8cd.appspot.com',
    iosClientId: '374257279074-37s9lu0vbcbtbmfkrnk35kj7eou3va7o.apps.googleusercontent.com',
    iosBundleId: 'com.flutter.dmintzer.tiktokClone',
  );
}
